---
abstract: 'represent any /etc/init.d/ script as ubic service'
author:
  - 'Vyacheslav Matyukhin <mmcleric@yandex-team.ru>'
build_requires:
  Test::More: 0
  Ubic::Result: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ubic-Service-InitScriptWrapper
requires:
  IPC::System::Simple: 0
  Ubic::Service::Skeleton: 0
  autodie: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/berekuk/Ubic-Service-InitScriptWrapper/issues
  homepage: http://github.com/berekuk/Ubic-Service-InitScriptWrapper/wiki
  repository: git://github.com/berekuk/Ubic-Service-InitScriptWrapper.git
version: 0.02
