---
abstract: 'represent any /etc/init.d/ script as ubic service'
author:
  - 'Vyacheslav Matyukhin <mmcleric@yandex-team.ru>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300007, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ubic-Service-InitScriptWrapper
resources:
  bugtracker: http://github.com/berekuk/Ubic-Service-InitScriptWrapper/issues
  homepage: http://github.com/berekuk/Ubic-Service-InitScriptWrapper/wiki
  repository: git://github.com/berekuk/Ubic-Service-InitScriptWrapper.git
version: 0.01
